# Generated by Django 3.1.1 on 2020-09-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Наименование')),
                ('units', models.CharField(choices=[('м', 'м'), ('м2', 'м2'), ('шт', 'шт')], max_length=10, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'abs-materials',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('client', models.CharField(max_length=50, verbose_name='Заказчик')),
                ('order_date', models.DateField(verbose_name='Дата приёма')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Кол-во')),
                ('status', models.IntegerField(choices=[(0, 'Ожидается'), (1, 'В производстве'), (2, 'На складе')], verbose_name='Статус')),
                ('details', models.CharField(blank=True, max_length=100, null=True, verbose_name='Характеристики (детали)')),
                ('for_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.absmaterial')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Склад',
                'db_table': 'stock',
            },
        ),
        migrations.AddField(
            model_name='absmaterial',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider'),
        ),
    ]
