# Generated by Django 3.1.1 on 2020-10-15 15:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200916_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='prod_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='absmaterial',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.folder', verbose_name='Папка'),
        ),
        migrations.AlterField(
            model_name='absmaterial',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='absmaterial',
            name='units',
            field=models.CharField(choices=[('м', 'м'), ('м²', 'м²'), ('шт', 'шт'), ('комп.', 'комп.'), ('лист', 'лист')], default='шт', max_length=10, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='material',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='material',
            name='for_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Для заказа'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.absmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидается'), (1, 'В производстве'), (2, 'На складе')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 10, 15), verbose_name='Дата приёма'),
        ),
    ]
