# Generated by Django 3.1.1 on 2020-10-27 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201015_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedMaterial',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.material')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Завершённые',
                'db_table': 'completed',
            },
            bases=('main.material',),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидается'), (1, 'На складе'), (2, 'В производстве')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 10, 27), verbose_name='Дата приёма'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Кол-во')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.absmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Для нового заказа',
                'db_table': 'tasks',
            },
        ),
    ]
