# Generated by Django 3.1.1 on 2020-11-06 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201102_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 11, 6), verbose_name='Дата приёма'),
        ),
        migrations.DeleteModel(
            name='CompletedMaterial',
        ),
    ]
