# Generated by Django 3.1.1 on 2020-11-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201106_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Кол-во')),
                ('details', models.CharField(blank=True, max_length=100, null=True, verbose_name='Детали')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('for_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Для заказа')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.absmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Завершённые',
                'db_table': 'completed',
            },
        ),
    ]
