# Generated by Django 3.1.1 on 2020-11-13 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_completedmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 11, 13), verbose_name='Дата приёма'),
        ),
    ]
