# Generated by Django 3.1.1 on 2020-11-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201113_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='for_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order'),
        ),
    ]
