# Generated by Django 3.1.1 on 2020-11-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_task_for_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='for_order',
        ),
        migrations.RemoveField(
            model_name='task',
            name='material',
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Не заказано'), (0, 'Ожидается'), (1, 'На складе'), (2, 'В производстве'), (3, 'Реализовано')], default=0, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='CompletedMaterial',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
