# Generated by Django 3.1.1 on 2020-11-14 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201113_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absmaterial',
            name='provider',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 11, 14), verbose_name='Дата приёма'),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
